name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env: 
      TF_VAR_public_key: $(cat ./ec2-key.pub)
      TF_VAR_key_name: "ec2-key"

    steps:

    - name: Checkout code
      uses: actions/checkout@v3


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Generate SSH Key Pair
      run: |
        ssh-keygen -t rsa -b 4096 -m PEM -f ec2-key -q -N ""


    - name: Import Key Pair into AWS
      run: |
        aws ec2 import-key-pair \
          --key-name ec2-key \
          --public-key-material fileb://ec2-key.pub
          
    - name: Deployment for Network
      run: |
        cd networks
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan


    - name: Deployment for Webservers
      run: |
        cd webservers
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan


    - name: Upload Both Keys
      uses: actions/upload-artifact@v3
      with:
        name: ec2-keys
        path: |
          ec2-key     
          ec2-key.pub
